#!/usr/bin/env bash


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# install composer package manager
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# make sure composer is up to date
composer selfupdate
