#!/usr/bin/env bash


# @param: name of the db
args_db_name=${1}

# @param: username of the db user
args_db_user=${2}

# @param: password of the db user
args_db_pass=${3}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# install MySQL
sudo apt-get install -qq mysql-server > /dev/null

# create database
mysql -uroot -e "create database ${args_db_name};" > /dev/null

# create mysql user
mysql -uroot -e "create user '${args_db_user}'@'localhost' identified by '${args_db_pass}';" > /dev/null

# grant all permissions to user on database
mysql -uroot -e "grant all privileges on '${args_db_name}'.* to '${args_db_user}'@'localhost';" > /dev/null
